/**
 * Shared FOF ledger rows (Postgres JSONB payload).
 * Client localStorage is a cache only.
 */

import { query } from "@/lib/db"
import type { StoredUser } from "@/lib/server/users"
import { canAccessInstructionRecords } from "@/lib/server/instruction-records"

export type OpsLedgerAttachment = {
  id: string
  name: string
  source?: "upload" | "email"
  confirmRecordId?: number
}

export type OpsLedgerRow = {
  id: string
  fof_fund_name: string
  fof_register_number: string | null
  transaction_type: string
  underlying_type: string | null
  underlying_fund_name: string
  underlying_beian_hao: string | null
  apply_date: string
  confirm_date: string
  confirmed_shares: string | null
  confirmed_amount: string | null
  confirmed_unit_nav: string | null
  transaction_fee: string | null
  performance_fee: string | null
  share_balance: string | null
  dividend_per_unit: string | null
  source: string | null
  remark: string | null
  instruction_id: string | null
  contract_attachment?: OpsLedgerAttachment | null
  confirm_attachment?: OpsLedgerAttachment | null
  /** Stable key for 估值表-generated rows (`val-{parent}-{und}-{date}`). */
  generation_key?: string | null
  /** When true, auto-generate will not overwrite this row. */
  locked?: boolean
  /** 手工核对状态：估值表生成后为待确认，批量/单条确认后为已确认。 */
  review_status?: "pending" | "confirmed"
  reviewed_by?: string | null
  reviewed_at?: string | null
}

let initPromise: Promise<void> | null = null

function asString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback
}

function asNullableString(value: unknown): string | null {
  if (value == null) return null
  return typeof value === "string" ? value : null
}

function normalizeAttachment(raw: unknown): OpsLedgerAttachment | null {
  if (!raw || typeof raw !== "object") return null
  const row = raw as Partial<OpsLedgerAttachment>
  const id = asString(row.id).trim()
  const name = asString(row.name).trim()
  if (!id || !name) return null
  return {
    id,
    name,
    source: row.source === "email" ? "email" : row.source === "upload" ? "upload" : undefined,
    confirmRecordId:
      typeof row.confirmRecordId === "number" && Number.isFinite(row.confirmRecordId)
        ? row.confirmRecordId
        : undefined,
  }
}

export function normalizeOpsLedgerRow(raw: unknown): OpsLedgerRow | null {
  if (!raw || typeof raw !== "object") return null
  const row = raw as Partial<OpsLedgerRow>
  const id = asString(row.id).trim()
  if (!id) return null
  const fof_fund_name = asString(row.fof_fund_name).trim()
  const underlying_fund_name = asString(row.underlying_fund_name).trim()
  const apply_date = asString(row.apply_date).trim()
  const confirm_date = asString(row.confirm_date).trim()
  if (!fof_fund_name || !underlying_fund_name || !apply_date || !confirm_date) return null

  return {
    id,
    fof_fund_name,
    fof_register_number: asNullableString(row.fof_register_number),
    transaction_type: asString(row.transaction_type),
    underlying_type: asNullableString(row.underlying_type),
    underlying_fund_name,
    underlying_beian_hao: asNullableString(row.underlying_beian_hao),
    apply_date,
    confirm_date,
    confirmed_shares: asNullableString(row.confirmed_shares),
    confirmed_amount: asNullableString(row.confirmed_amount),
    confirmed_unit_nav: asNullableString(row.confirmed_unit_nav),
    transaction_fee: asNullableString(row.transaction_fee),
    performance_fee: asNullableString(row.performance_fee),
    share_balance: asNullableString(row.share_balance),
    dividend_per_unit: asNullableString(row.dividend_per_unit),
    source: asNullableString(row.source),
    remark: asNullableString(row.remark),
    instruction_id: asNullableString(row.instruction_id),
    contract_attachment: normalizeAttachment(row.contract_attachment),
    confirm_attachment: normalizeAttachment(row.confirm_attachment),
    generation_key: asNullableString(row.generation_key),
    locked: row.locked === true,
    review_status:
      row.review_status === "confirmed" || row.review_status === "pending"
        ? row.review_status
        : asString(row.source) === "指令"
          ? "confirmed"
          : "pending",
    reviewed_by: asNullableString(row.reviewed_by),
    reviewed_at: asNullableString(row.reviewed_at),
  }
}

export function isAutoGeneratedLedgerSource(source: string | null | undefined): boolean {
  return Boolean(source && source.startsWith("估值表"))
}

export function isLedgerRowConfirmed(row: Pick<OpsLedgerRow, "review_status">): boolean {
  return row.review_status === "confirmed"
}

export function isProtectedLedgerRow(row: Pick<OpsLedgerRow, "locked" | "source" | "review_status">): boolean {
  if (row.locked) return true
  if (row.review_status === "confirmed") return true
  const source = row.source || ""
  return source === "手工" || source === "手工修正" || source === "指令" || source === "批量上传"
}

function ledgerBeianFamilyKey(code: string | null | undefined): string {
  const raw = String(code ?? "").trim().toUpperCase()
  if (!raw) return ""
  let base = raw.replace(/[ABC]$/u, "")
  if (base.startsWith("S") && base.length > 1 && /^S[A-Z][A-Z0-9]{4,7}$/u.test(base)) {
    base = base.slice(1)
  }
  return base
}

async function ensureTable() {
  if (!initPromise) {
    initPromise = (async () => {
      await query(`
        CREATE TABLE IF NOT EXISTS ops_ledger_records (
          id          TEXT PRIMARY KEY,
          created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          payload     JSONB NOT NULL
        )
      `)
      await query(`
        CREATE INDEX IF NOT EXISTS idx_ops_ledger_records_updated
          ON ops_ledger_records (updated_at DESC)
      `)
      await query(`
        CREATE INDEX IF NOT EXISTS idx_ops_ledger_records_instruction
          ON ops_ledger_records ((payload->>'instruction_id'))
      `)
      await query(`
        CREATE TABLE IF NOT EXISTS ops_ledger_generation_skips (
          generation_key TEXT PRIMARY KEY,
          skipped_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
      `)
    })().catch((e) => {
      initPromise = null
      throw e
    })
  }
  await initPromise
}

/** Any logged-in MA account may view and edit the shared ledger. */
export function canAccessOpsLedger(
  user: Pick<StoredUser, "id" | "role" | "permissions"> | null | undefined,
): boolean {
  return canAccessInstructionRecords(user)
}

function parsePayload(payload: OpsLedgerRow | string): unknown {
  if (typeof payload === "string") {
    try {
      return JSON.parse(payload) as unknown
    } catch {
      return null
    }
  }
  return payload
}

export async function listServerOpsLedgerRecords(): Promise<OpsLedgerRow[]> {
  await ensureTable()
  const rows = await query<{ payload: OpsLedgerRow | string }>(
    `SELECT payload
       FROM ops_ledger_records
      ORDER BY updated_at DESC`,
  )
  const out: OpsLedgerRow[] = []
  for (const row of rows) {
    const record = normalizeOpsLedgerRow(parsePayload(row.payload))
    if (record) out.push(record)
  }
  return out
}

export type ListServerOpsLedgerOptions = {
  fof_register_number?: string | null
  fof_fund_name?: string | null
  underlying_beian_hao?: string | null
  /** Substring match on 底层基金名称 / 备案号 only. */
  underlying_fund_name?: string | null
  /** Match parent FOF or underlying (product detail 交易分析). */
  product_beian_hao?: string | null
  apply_date_from?: string
  apply_date_to?: string
  underlying_name_q?: string
  review_status?: "pending" | "confirmed" | "all" | ""
  sort?: "apply_date" | "confirm_date" | ""
  dir?: "asc" | "desc"
  page?: number
  pageSize?: number
}

export function filterOpsLedgerRecords(
  all: OpsLedgerRow[],
  options?: ListServerOpsLedgerOptions,
): {
  data: OpsLedgerRow[]
  total: number
  page: number
  pageSize: number
  totalPages: number
} {
  let rows = [...all]
  const fofReg = options?.fof_register_number?.trim()
  const fofName = options?.fof_fund_name?.trim()
  const undBeian = options?.underlying_beian_hao?.trim()
  const undName = options?.underlying_fund_name?.trim()
  const productBeian = options?.product_beian_hao?.trim()
  const from = options?.apply_date_from?.trim()
  const to = options?.apply_date_to?.trim()
  const nameQ = options?.underlying_name_q?.trim()

  if (productBeian) {
    const family = ledgerBeianFamilyKey(productBeian)
    rows = rows.filter((r) => {
      if (r.fof_register_number === productBeian || r.underlying_beian_hao === productBeian) return true
      if (family && ledgerBeianFamilyKey(r.fof_register_number) === family) return true
      if (family && ledgerBeianFamilyKey(r.underlying_beian_hao) === family) return true
      return false
    })
  }
  if (fofReg || fofName) {
    const nameNeedle = fofName?.toLowerCase() ?? ""
    const fofFam = ledgerBeianFamilyKey(fofReg)
    rows = rows.filter((r) => {
      if (fofReg) {
        if (r.fof_register_number === fofReg) return true
        if (fofFam && ledgerBeianFamilyKey(r.fof_register_number) === fofFam) return true
      }
      if (nameNeedle) {
        if (r.fof_fund_name.toLowerCase().includes(nameNeedle)) return true
        if ((r.fof_register_number || "").toLowerCase().includes(nameNeedle)) return true
      }
      return false
    })
  }
  if (undBeian || undName) {
    const nameNeedle = undName?.toLowerCase() ?? ""
    const undFam = ledgerBeianFamilyKey(undBeian)
    rows = rows.filter((r) => {
      if (undBeian) {
        if (r.underlying_beian_hao === undBeian) return true
        if (undFam && ledgerBeianFamilyKey(r.underlying_beian_hao) === undFam) return true
      }
      if (nameNeedle) {
        if (r.underlying_fund_name.toLowerCase().includes(nameNeedle)) return true
        if ((r.underlying_beian_hao || "").toLowerCase().includes(nameNeedle)) return true
      }
      return false
    })
  }
  if (from) rows = rows.filter((r) => r.apply_date >= from)
  if (to) rows = rows.filter((r) => r.apply_date <= to)
  if (nameQ) {
    rows = rows.filter(
      (r) =>
        r.underlying_fund_name.includes(nameQ)
        || r.fof_fund_name.includes(nameQ),
    )
  }
  const reviewStatus = options?.review_status
  if (reviewStatus === "pending" || reviewStatus === "confirmed") {
    rows = rows.filter((r) => (r.review_status || "pending") === reviewStatus)
  }

  const sortKey = options?.sort || "apply_date"
  const dir = options?.dir === "asc" ? 1 : -1
  rows.sort((a, b) => {
    const av = sortKey === "confirm_date" ? a.confirm_date : a.apply_date
    const bv = sortKey === "confirm_date" ? b.confirm_date : b.apply_date
    if (av < bv) return -1 * dir
    if (av > bv) return 1 * dir
    return 0
  })

  const page = Math.max(1, options?.page ?? 1)
  const pageSize = Math.min(200, Math.max(1, options?.pageSize ?? 50))
  const total = rows.length
  const totalPages = Math.max(1, Math.ceil(total / pageSize))
  const start = (page - 1) * pageSize
  return {
    data: rows.slice(start, start + pageSize),
    total,
    page,
    pageSize,
    totalPages,
  }
}

export async function confirmServerOpsLedgerRecords(
  ids: string[],
  reviewer: { id: string; name: string },
): Promise<OpsLedgerRow[]> {
  await ensureTable()
  const idSet = new Set(ids.map((id) => String(id || "").trim()).filter(Boolean))
  if (idSet.size === 0) return []
  const existing = await listServerOpsLedgerRecords()
  const now = new Date().toISOString()
  const reviewerName = reviewer.name.trim() || reviewer.id
  const toSave = existing
    .filter((row) => idSet.has(row.id))
    .map((row) => ({
      ...row,
      review_status: "confirmed" as const,
      reviewed_by: reviewerName,
      reviewed_at: now,
      locked: true,
    }))
  if (toSave.length === 0) return []
  return upsertServerOpsLedgerRecords(toSave)
}

export async function upsertServerOpsLedgerRecord(input: unknown): Promise<OpsLedgerRow> {
  await ensureTable()
  const record = normalizeOpsLedgerRow(input)
  if (!record) throw new Error("台账数据无效")

  await query(
    `INSERT INTO ops_ledger_records (id, created_at, updated_at, payload)
     VALUES ($1, NOW(), NOW(), $2::jsonb)
     ON CONFLICT (id) DO UPDATE SET
       updated_at = NOW(),
       payload = EXCLUDED.payload`,
    [record.id, JSON.stringify(record)],
  )
  return record
}

export async function upsertServerOpsLedgerRecords(
  inputs: unknown[],
): Promise<OpsLedgerRow[]> {
  await ensureTable()
  const saved: OpsLedgerRow[] = []
  const payload: Array<{ id: string; payload: OpsLedgerRow }> = []
  for (const input of inputs) {
    const record = normalizeOpsLedgerRow(input)
    if (!record) continue
    saved.push(record)
    payload.push({ id: record.id, payload: record })
  }
  const chunkSize = 200
  for (let i = 0; i < payload.length; i += chunkSize) {
    const chunk = payload.slice(i, i + chunkSize)
    await query(
      `INSERT INTO ops_ledger_records (id, created_at, updated_at, payload)
       SELECT x.id, NOW(), NOW(), x.payload
         FROM jsonb_to_recordset($1::jsonb) AS x(id text, payload jsonb)
       ON CONFLICT (id) DO UPDATE SET
         updated_at = NOW(),
         payload = EXCLUDED.payload`,
      [JSON.stringify(chunk)],
    )
  }
  return saved
}

export async function listLedgerGenerationSkips(): Promise<string[]> {
  await ensureTable()
  const rows = await query<{ generation_key: string }>(
    `SELECT generation_key FROM ops_ledger_generation_skips`,
  )
  return rows.map((row) => row.generation_key)
}

export async function recordLedgerGenerationSkip(generationKey: string): Promise<void> {
  await ensureTable()
  const key = String(generationKey || "").trim()
  if (!key) return
  await query(
    `INSERT INTO ops_ledger_generation_skips (generation_key)
     VALUES ($1)
     ON CONFLICT (generation_key) DO NOTHING`,
    [key],
  )
}

export async function deleteServerOpsLedgerRecord(id: string): Promise<boolean> {
  await ensureTable()
  const safeId = String(id || "").trim()
  if (!safeId) return false
  const existing = await query<{ payload: OpsLedgerRow | string }>(
    `SELECT payload FROM ops_ledger_records WHERE id = $1 LIMIT 1`,
    [safeId],
  )
  const record = existing[0] ? normalizeOpsLedgerRow(parsePayload(existing[0].payload)) : null
  const skipKey = record?.generation_key || (safeId.startsWith("val-") ? safeId : "")
  if (skipKey) await recordLedgerGenerationSkip(skipKey)
  const rows = await query<{ id: string }>(
    `DELETE FROM ops_ledger_records WHERE id = $1 RETURNING id`,
    [safeId],
  )
  return rows.length > 0
}

export async function deleteServerOpsLedgerByInstructionId(
  instructionId: string,
): Promise<number> {
  await ensureTable()
  const safeId = String(instructionId || "").trim()
  if (!safeId) return 0
  const rows = await query<{ id: string }>(
    `DELETE FROM ops_ledger_records
      WHERE payload->>'instruction_id' = $1
      RETURNING id`,
    [safeId],
  )
  return rows.length
}
