/** Chinese display labels for financial / commodity option underlyings (key → name). */
export const UNDERLYING_CN_LABELS: Record<string, string> = {
  "50etf": "50ETF (510050)",
  "50index": "50股指 (HO)",
  "300etf": "300ETF (510300)",
  "300etf_sz": "300ETF (159919)",
  "300index": "300股指 (IO)",
  "500etf": "500ETF (510500)",
  "500etf_sz": "500ETF (159922)",
  "1000index": "1000股指 (MO)",
  cyb: "创业板ETF",
  kcb: "科创50 (588000)",
  kcb_efund: "科创50 (588080)",
  "100etf": "深证100ETF",
  // Commodity options
  a: "豆一",
  b: "豆二",
  m: "豆粕",
  y: "豆油",
  p: "棕榈油",
  c: "玉米",
  cs: "玉米淀粉",
  jd: "鸡蛋",
  lh: "生猪",
  lg: "原木",
  sr: "白糖",
  cf: "棉花",
  oi: "菜油",
  rm: "菜粕",
  pk: "花生",
  ap: "苹果",
  cj: "红枣",
  i: "铁矿石",
  rb: "螺纹钢",
  sf: "硅铁",
  sm: "锰硅",
  zc: "动力煤",
  cu: "铜",
  al: "铝",
  zn: "锌",
  pb: "铅",
  ni: "镍",
  sn: "锡",
  ao: "氧化铝",
  au: "黄金",
  ag: "白银",
  sc: "原油",
  ru: "天胶",
  br: "丁二烯橡胶",
  nr: "20号胶",
  fu: "燃料油",
  l: "聚乙烯",
  v: "聚氯乙烯",
  pp: "聚丙烯",
  eg: "乙二醇",
  eb: "苯乙烯",
  pg: "LPG",
  ta: "PTA",
  ma: "甲醇",
  fg: "玻璃",
  sa: "纯碱",
  sh: "烧碱",
  ur: "尿素",
  pf: "短纤",
  px: "对二甲苯",
  pr: "瓶片",
  si: "工业硅",
  lc: "碳酸锂",
  ps: "多晶硅",
}

export function underlyingCnLabel(key: string, fallback?: string): string {
  return UNDERLYING_CN_LABELS[key] ?? fallback ?? key
}

/** Short Chinese name for chart titles (e.g. "上证50 ETF"). */
export const UNDERLYING_CHART_LABELS: Record<string, string> = {
  "50etf": "上证50 ETF",
  "50index": "上证50 股指",
  "300etf": "沪深300 ETF",
  "300etf_sz": "沪深300 ETF",
  "300index": "沪深300 股指",
  "500etf": "中证500 ETF",
  "500etf_sz": "中证500 ETF",
  "1000index": "中证1000 股指",
  cyb: "创业板 ETF",
  kcb: "科创50 ETF",
  kcb_efund: "科创50 ETF",
  "100etf": "深证100 ETF",
}

export function underlyingChartLabel(key: string, fallback?: string): string {
  return UNDERLYING_CHART_LABELS[key] ?? fallback ?? underlyingCnLabel(key, fallback)
}
